// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanRun
{
    internal sealed partial class Vsix
    {
        public const string Id = "CleanRun.efa888c2-8340-416c-b3d1-babf591e17cf";
        public const string Name = "CleanRun";
        public const string Description = @"CleanRun allows you to clean, build and run a project with 1 button";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Julian Slonim";
        public const string Tags = "";
    }
}
